### ISSUE TITLE
proxy thumbnail pic & preview vid

### ISSUE THREAD

**Issue by raisedhand** [hazycora/tv.hazy.su#1]
hi hazycora ,
at the first special thanks to you , please if it's possible proxy thumbnail pic & preview-autoplay-clip of videos. we're living in iran & having strong censorship on internet.
waiting for your response
finest regards

**Comment by hazycora** [comment]
Hello! I will have this be a setting. Sorry I didn't get back to you sooner!

**Comment by hazycora** [comment]
Actually, I see no reason anyone wouldn't want this- I'll make it proxy all thumbnails and images and I'll implement it as a setting enabled by default in the future in case anyone has issues with it.

**Comment by hazycora** [comment]
It has been added to the source code. https://github.com/hazycora/tv.hazy.su/commit/f19924ef9932351eaeec65a96013b378f8d777e6
Code on https://tv.hazy.su is also up to date and is now proxying thumbnails.
Thanks for the suggestion!

**Comment by raisedhand** [comment]
hi hazycora,
please proxy search query result thumbnail & video previews too.
& if it's possible add auto generate captions for all languages too.
waiting for your response
finest regards

**Comment by hazycora** [comment]
Topic of proxying thumbnails will switch to your new issue- Sorry that I didn't notice search result thumbnails were still not proxied! Easy fix. Will do ASAP.
On separate but important topic, you mention auto generated captions- It does check all caption tracks on the video and *should* add them for every language that YouTube itself has for the video. It shouldn't be specific to any language, so it should work for all of them. Could you give an example for something that should have automatic captions in some language but doesn't using this repo? Thanks in advance :)
